services:
  app:
    build: docker/swoole
    restart: unless-stopped
    ports:
      - "80:80"
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
      - redis
    networks:
      - laravel

  mysql:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      LANG: C.UTF-8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - laravel

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel

  mailpit:
    image: axllent/mailpit:latest
    restart: on-failure
    tty: true
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
    driver: bridge
