services:
  app:
    build: docker/nginx
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - ssl_certificates:/etc/nginx/ssl
    depends_on:
      - mysql
      - redis
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/certs/server.crt:/etc/ssl/certs/server.crt
      - ./nginx/certs/server.key:/etc/ssl/private/server.key
    depends_on:
      - app
    networks:
      - laravel

  mysql:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-root}
      LANG: C.UTF-8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-root}
    networks:
      - laravel

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - laravel

  mailpit:
    image: axllent/mailpit:latest
    restart: on-failure
    tty: true
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - laravel

volumes:
  mysql_data:
  ssl_certificates:

networks:
  laravel:
    driver: bridge
