#!/bin/sh

if [ "$1" = "--frankenphp" ] || [ "$1" = "-f" ]; then
  docker compose -f compose.frankenphp.yml exec app bash
elif [ "$1" = "--swoole" ] || [ "$1" = "-s" ]; then
  docker compose -f compose.swoole.yml exec app bash
else
    echo "Error: You must specify either --frankenphp (-f) or --swoole (-s)."
    echo "Ex: $0 --frankenphp"
    echo "Ex: $0 -f"
    exit 1
fi
