#!/bin/bash

composer clear-cache && composer install --no-dev --optimize-autoloader --prefer-dist --no-interaction --no-progress

php artisan migrate --force
php artisan storage:link
php artisan config:cache
php artisan route:cache
php artisan view:cache
php artisan filament:optimize

# Inicia o Supervisor para gerenciar nginx, queue worker e schedule worker
service nginx start
exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
